In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from IPython.display import Image
from sklearn import preprocessing
from sklearn import utils
import pydotplus
from sklearn.model_selection import GridSearchCV
import warnings


from Load_Data_Clean import load_dataset
images, probabilities = load_dataset()

In [4]:
print(images)
print(probabilities)

[[[14 14 14 ...  9  9  9]
  [15 15 15 ... 10  9  9]
  [15 15 16 ... 10 10 10]
  ...
  [29 29 29 ... 19 18  4]
  [29 29 29 ... 18 18  4]
  [29 29 29 ... 18 18  4]]

 [[29 29 29 ... 17 16  3]
  [29 29 29 ... 17 16  3]
  [29 29 29 ... 16 15  3]
  ...
  [21 22 21 ... 12 12 11]
  [20 20 20 ... 12 12 11]
  [19 19 18 ... 12 12 10]]

 [[29 29 30 ... 19 18  4]
  [29 30 30 ... 19 18  4]
  [30 30 31 ... 18 18  3]
  ...
  [35 35 35 ... 21 12  0]
  [35 35 35 ... 21 12  0]
  [35 35 35 ... 21 12  0]]

 ...

 [[66 65 62 ... 62 62 62]
  [64 62 61 ... 60 60 61]
  [63 61 59 ... 61 60 60]
  ...
  [45 50 55 ... 57 51 47]
  [45 47 48 ... 52 49 46]
  [43 43 44 ... 48 46 44]]

 [[64 65 64 ... 68 69 67]
  [62 62 63 ... 66 67 66]
  [61 60 61 ... 68 67 67]
  ...
  [47 45 46 ... 54 48 48]
  [44 42 42 ... 53 47 47]
  [44 41 41 ... 51 46 46]]

 [[67 68 66 ... 64 64 63]
  [67 67 66 ... 63 62 63]
  [67 66 64 ... 66 63 63]
  ...
  [48 48 49 ... 65 55 50]
  [46 45 45 ... 59 51 47]
  [44 43 42 ... 51 47 45]]]
[1. 1. 1. 

In [5]:
x = images
y = probabilities

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25)

x_train.shape,y_train.shape

number_of_samples,width,length = x_train.shape
x_train_2 = x_train.reshape((number_of_samples,width*length))

lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y_train)

In [6]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train_2,y_transformed)

DecisionTreeClassifier()

In [8]:
number_of_samples,width,length = x_test.shape
x_test_2 = x_test.reshape((number_of_samples,width*length))

lab = preprocessing.LabelEncoder()
y_transformed_2 = lab.fit_transform(y_test)

x_pred = dtc.predict(x_train_2)
y_pred = dtc.predict(x_test_2)

print("Classification Report: \n\n",classification_report(y_transformed_2,y_pred, target_names = ['0', '1']))
print("Accuracy: ",accuracy_score(y_transformed_2, y_pred))

Classification Report: 

               precision    recall  f1-score   support

           0       0.82      0.77      0.79       393
           1       0.52      0.60      0.55       163

    accuracy                           0.72       556
   macro avg       0.67      0.68      0.67       556
weighted avg       0.73      0.72      0.72       556

Accuracy:  0.7176258992805755
